spring.application.name=HotelManagementProject

# Server port ==========
server.port=8080

# SQL Server DataSource ==========
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hotel_booking_system;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate ==========
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (debug) ==========
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf ==========
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# PayOS ==========
PAYOS_CLIENT_ID=37c14d15-a7d0-4ef0-a135-9436f5b47fc9
PAYOS_API_KEY=078aa3e6-1fb4-49d5-8d3c-11d944ee5870
PAYOS_CHECKSUM_KEY=7c37399c4622d828c44ee4762fe3f94e8a76742e9ab338f9a11f94bf48091c74

# Gemini AI Chatbot ==========
gemini.api.key=KEY
gemini.api.model=gemini-3.1-flash-lite-preview

